AWSTemplateFormatVersion: 2010-09-09
Parameters:
  mykeypair:
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroupIP:
    Type: String
    Default: 0.0.0.0/0
    Description: Introduce la IP para hacer whitelist en nuestro SG.
Resources:
  MiprimeraInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-053b0d53c279acc90
      KeyName: keypair-oregon
      InstanceType: t2.micro
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "gp3"
          DeleteOnTermination: "true"
          VolumeSize: "10"
      SecurityGroups:
      - !Ref InstanceSecurityGroup
      UserData: 
        Fn::Base64: 
          !Sub |
#!/bin/bash

apt update
apt install apache2 -y
systemctl start apache2
systemctl enable apache2
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref SecurityGroupIP
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 443
          CidrIp: !Ref SecurityGroupIP